/*
 * ReadsColorPanel.java
 *
 * Created on October 16, 2008, 11:06 AM
 */
package Magic.Analysis.Merage;

import Magic.Analysis.Merage.MergePara.MutimatchPolicy;
import utils.swing.ExpandPanel.ExpandPanelAbstract;
//import Magic.Analysis.MergePara.SpeicesType;
import Magic.Analysis.Merage.MergePara.SNPType;
import Magic.Units.File.Parameter.StringRep;
import Magic.Units.Track.Track;
import java.util.Arrays;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.SpinnerListModel;
import javax.swing.SpinnerModel;
import org.biojava.bio.seq.RNATools;
import utils.swing.SwingUtil;

/**
 *
 * @author Huabin Hou
 */
public class MergeSettingtPanel extends JPanel implements ExpandPanelAbstract {

    private MergeAnnotationDialog parent;
    String[] clusterArray = {StringRep.AutoCluster, StringRep.UserDefineCluster, StringRep.NoCluster, StringRep.NotCDS};
    SpinnerModel clusterModel = new SpinnerListModel(Arrays.asList(clusterArray));

    /** Creates new form ReadsColorPanel */
    public MergeSettingtPanel(MergeAnnotationDialog parent) {

        initComponents();
        this.parent = parent;
        init();
    }

    public void init() {
        Iterator<String> it = RNATools.getGeneticCodeNames().iterator();
        int i = 0;
        while (it.hasNext()) {
            String name = it.next();
            code.addItem(name);

        }
        code.setSelectedItem("EUPLOTID_NUCLEAR");
       /* for (Track annoTrack : parent.annoTracks) {
            if (annoTrack.trackSet.format.equals(StringRep.PTT)) {
                cluster.setValue(StringRep.NoCluster);
            }
        }*/


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanelSNPType = new javax.swing.JPanel();
        synonymous = new javax.swing.JCheckBox();
        missense = new javax.swing.JCheckBox();
        nonsense = new javax.swing.JCheckBox();
        readthrough = new javax.swing.JCheckBox();
        spliceSite = new javax.swing.JCheckBox();
        intron = new javax.swing.JCheckBox();
        UTR5 = new javax.swing.JCheckBox();
        UTR3 = new javax.swing.JCheckBox();
        intergenic = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Pooled = new javax.swing.JRadioButton();
        AutoSeparate = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        Overlap = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        multi = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        code = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setFont(new java.awt.Font("Times New Roman", 0, 12));
        setMaximumSize(new java.awt.Dimension(500, 350));
        setPreferredSize(new java.awt.Dimension(500, 350));

        jPanelSNPType.setBorder(javax.swing.BorderFactory.createTitledBorder("Select SNPs type"));

        synonymous.setSelected(true);
        synonymous.setText("Synonymous");

        missense.setSelected(true);
        missense.setText("Missense");

        nonsense.setSelected(true);
        nonsense.setText("Nonsense");

        readthrough.setSelected(true);
        readthrough.setText("Readthrough");

        spliceSite.setSelected(true);
        spliceSite.setText("Splice site");

        intron.setSelected(true);
        intron.setText("Intron");

        UTR5.setSelected(true);
        UTR5.setText("5' UTR");

        UTR3.setSelected(true);
        UTR3.setText("3' UTR");

        intergenic.setSelected(true);
        intergenic.setText("Intergenic");

        org.jdesktop.layout.GroupLayout jPanelSNPTypeLayout = new org.jdesktop.layout.GroupLayout(jPanelSNPType);
        jPanelSNPType.setLayout(jPanelSNPTypeLayout);
        jPanelSNPTypeLayout.setHorizontalGroup(
            jPanelSNPTypeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelSNPTypeLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelSNPTypeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(synonymous)
                    .add(missense)
                    .add(nonsense)
                    .add(readthrough)
                    .add(spliceSite)
                    .add(intron)
                    .add(UTR5)
                    .add(UTR3)
                    .add(intergenic))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanelSNPTypeLayout.setVerticalGroup(
            jPanelSNPTypeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelSNPTypeLayout.createSequentialGroup()
                .addContainerGap()
                .add(synonymous)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(missense)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(nonsense)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(readthrough)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(spliceSite)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(intron)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(UTR5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(UTR3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(intergenic)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Outout policy"));

        buttonGroup1.add(Pooled);
        Pooled.setSelected(true);
        Pooled.setText("Pooled");

        buttonGroup1.add(AutoSeparate);
        AutoSeparate.setText("Auto separate");

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Pooled)
                    .add(AutoSeparate))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(Pooled)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(AutoSeparate))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Correlate policy"));

        buttonGroup2.add(Overlap);
        Overlap.setSelected(true);
        Overlap.setText("Overlap");

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Contain");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Overlap)
                    .add(jRadioButton2))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(Overlap)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jRadioButton2))
        );

        multi.setModel(new javax.swing.DefaultComboBoxModel(new MutimatchPolicy[] { MutimatchPolicy.Priority, MutimatchPolicy.Random, MutimatchPolicy.All}));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel20.setText("Mutimatch policy");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel17.setText("Genetic code");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel20)
                            .add(jLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(code, 0, 179, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, multi, 0, 179, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel20)
                    .add(multi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(34, 34, 34)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(code, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel17))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelSNPType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanelSNPType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(194, 194, 194)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton1)
                .add(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean setting() {
        if (Overlap.isSelected()) {
            MergePara.currentCorrelatePolicy = MergePara.CorrelatePolicy.Overlap;
        } else {
            MergePara.currentCorrelatePolicy = MergePara.CorrelatePolicy.Contain;
        }
        if (Pooled.isSelected()) {
            MergePara.currentOutputPolicy = MergePara.OutputPolicy.Pooled;
        } else {
            MergePara.currentOutputPolicy = MergePara.OutputPolicy.AutoSeparate;
        }
       
        MergePara.currentMutimatchPolicy =(MutimatchPolicy) multi.getSelectedItem();
     //   MergePara.clusterString = (String) cluster.getValue();

        MergePara.translationTable = (String) code.getSelectedItem();

        setSNPType();
        return true;
    }

    public void setSNPType() {

/*        Vector<Enum> enums = SwingUtil.setJCheckBoxParaByComponent(this, MergePara.SNPType.class);
        MergePara.snpTypes = new Vector<SNPType>();
        for (Enum enume : enums) {
            MergePara.snpTypes.add((SNPType) enume);
        }*/
    }

    public JPanel getPanel() {
        return jPanelSNPType;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        parent.submit();
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AutoSeparate;
    private javax.swing.JRadioButton Overlap;
    private javax.swing.JRadioButton Pooled;
    private javax.swing.JCheckBox UTR3;
    private javax.swing.JCheckBox UTR5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox code;
    private javax.swing.JCheckBox intergenic;
    private javax.swing.JCheckBox intron;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelSNPType;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JCheckBox missense;
    private javax.swing.JComboBox multi;
    private javax.swing.JCheckBox nonsense;
    private javax.swing.JCheckBox readthrough;
    private javax.swing.JCheckBox spliceSite;
    private javax.swing.JCheckBox synonymous;
    // End of variables declaration//GEN-END:variables
}
