/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectMainAnnotation.java
 *
 * Created on Nov 15, 2009, 6:46:44 PM
 */
package Magic.Analysis.Merage;

import Magic.Units.Gui.Task.LoadTrackTask;
import Magic.WinMain.MagicFrame;
import Magic.Units.File.FileFormat;
import Magic.Units.Main.SeeEggMethods;

import Magic.Units.File.Parameter.Log;
import Magic.Units.File.Parameter.StringRep;

import Magic.Units.Track.Track;
import Magic.Units.File.FastaFile;
import Magic.Units.File.Parameter.ForEverStatic;
import Magic.Units.Gui.Task.NewProgress;
import java.io.File;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import utils.FileUtil;
import utils.ReportInfo;
import utils.ForMagic;
import utils.swing.SwingUtil;

/**
 *
 * @author Huabin Hou
 */
public class MergeAnnotationMain extends javax.swing.JDialog {

    public DefaultListModel model1 = new DefaultListModel();
    MagicFrame parent;
    // public String mainAnnoFile;
    public ArrayList<String> annoFiles = new ArrayList<String>();
    //DataImportBean projectProperty;
    private ArrayList<Track> cdssListTrack = new ArrayList<Track>();

    /** Creates new form SelectMainAnnotation */
    public MergeAnnotationMain(javax.swing.JFrame parent, ArrayList<Track> annoTrack, Track mainAnnoTrack) {
        super(parent, false);
        initComponents();
        this.parent = (MagicFrame) parent;
        Main_annotaion.setText(mainAnnoTrack.trackSet.filename);
        Output.setText(FileUtil.getNoTypePart(mainAnnoTrack.trackSet.filename) + ".gff");
        Refrenece.setText(Log.instance().reference.refile);
        for (Track track : annoTrack) {
            annoFiles.add(track.trackSet.filename);
        }
        setVectorFiles(annoFiles);
        SwingUtil.setLocation(this);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Main_annotaion = new javax.swing.JTextField();
        main_add_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Annotation_file = new javax.swing.JList();
        q_add_button = new javax.swing.JButton();
        remove_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Output = new javax.swing.JTextField();
        output_add_button1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Refrenece = new javax.swing.JTextField();
        ref_add_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main anntation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel6.setFont(new java.awt.Font("Times New Roman", 0, 12));

        Main_annotaion.setFont(new java.awt.Font("Times New Roman", 0, 12));
        Main_annotaion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_annotaionActionPerformed(evt);
            }
        });

        main_add_button.setFont(new java.awt.Font("Times New Roman", 0, 12));
        main_add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        main_add_button.setMargin(new java.awt.Insets(2, 2, 2, 2));
        main_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_add_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main_annotaion, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(main_add_button)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(main_add_button)
                    .addComponent(Main_annotaion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Annotation file", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        Annotation_file.setFont(new java.awt.Font("Times New Roman", 0, 16));
        Annotation_file.setModel(model1);
        jScrollPane1.setViewportView(Annotation_file);

        q_add_button.setFont(new java.awt.Font("Times New Roman", 0, 12));
        q_add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        q_add_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        q_add_button.setMargin(new java.awt.Insets(2, 2, 2, 2));
        q_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q_add_buttonActionPerformed(evt);
            }
        });

        remove_button.setFont(new java.awt.Font("Times New Roman", 0, 16));
        remove_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/remove.png"))); // NOI18N
        remove_button.setMargin(new java.awt.Insets(2, 2, 2, 2));
        remove_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_buttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remove_button)
                    .addComponent(q_add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(q_add_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(remove_button))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Output", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Times New Roman", 0, 12));

        Output.setFont(new java.awt.Font("Times New Roman", 0, 12));
        Output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputActionPerformed(evt);
            }
        });

        output_add_button1.setFont(new java.awt.Font("Times New Roman", 0, 12));
        output_add_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        output_add_button1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        output_add_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                output_add_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(output_add_button1)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(output_add_button1)
                    .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reference", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel8.setFont(new java.awt.Font("Times New Roman", 0, 12));

        Refrenece.setFont(new java.awt.Font("Times New Roman", 0, 12));
        Refrenece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreneceActionPerformed(evt);
            }
        });

        ref_add_button.setFont(new java.awt.Font("Times New Roman", 0, 12));
        ref_add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        ref_add_button.setMargin(new java.awt.Insets(2, 2, 2, 2));
        ref_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ref_add_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Refrenece, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ref_add_button)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ref_add_button)
                    .addComponent(Refrenece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Main_annotaionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_annotaionActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Main_annotaionActionPerformed

    private void main_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_add_buttonActionPerformed
        // TODO add your handling code here:


        String name = SwingUtil.getOpenFileByChooser(null, null, parent);
        if (name == null) {
            return;
        }

        String fileType = FileFormat.checkFileFormatByContent(name);

        if (FileFormat.isSurportedSNP(fileType)) {
            Main_annotaion.setText(name);
        } else {
            int answerConfirmation = JOptionPane.showConfirmDialog(parent, "Not surported format!", "ERROR", JOptionPane.DEFAULT_OPTION);
            switch (answerConfirmation) {
                case 0:
                case 1:
                    return;
            }

        }


    }//GEN-LAST:event_main_add_buttonActionPerformed

    private void q_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q_add_buttonActionPerformed

        JFileChooser filechooser = new JFileChooser();
        filechooser.setMultiSelectionEnabled(true);
        // //System.out.println(LogBean.getInstance().global.CURRENT_PATH+"  LogBean.getInstance().global.CURRENT_PATH==========================");
        filechooser.setCurrentDirectory(new File(ForEverStatic.CURRENT_PATH));
        int answer = filechooser.showOpenDialog(this);
        switch (answer) {
            case JFileChooser.APPROVE_OPTION:
                break;
            case JFileChooser.CANCEL_OPTION:
                return;
        }
        File[] files = filechooser.getSelectedFiles();
        if (files == null || files.length == 0) {
            return;
        }
        ForEverStatic.CURRENT_PATH = files[0].getParent();
        String unexistFile = "";
        for (int i = 0; i < files.length; i++) {
            File file = files[i];
            //System.out.println("Add: " + file.getName());
            String name = file.getAbsolutePath();
            try {
                name = file.getCanonicalPath();
            } catch (Exception e) {
                //System.out.println(e.getMessage());
            }

            String format = FileFormat.checkFileFormatByContent(name);


            if (FileFormat.checkAnnotationFormat(format)) {
                model1.addElement(name);

            } else {
                String name1 = file.getName();

                if (SeeEggMethods.checkFileExist(name1)) {
                }
                unexistFile = unexistFile + "\t" + name1;

            }
        }
        if (!unexistFile.equals("")) {
            JOptionPane.showMessageDialog(this, unexistFile + " not surported  format, please check", "Warnning", JOptionPane.OK_OPTION);
        }
}//GEN-LAST:event_q_add_buttonActionPerformed

    private void remove_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_buttonActionPerformed
        int[] indices = Annotation_file.getSelectedIndices();
        if (indices != null) {
            for (int i = indices.length - 1; i >= 0; i--) {
                model1.removeElementAt(indices[i]);
                //  model2.removeElementAt(indices[i]);
            }
            Annotation_file.setSelectedIndex(-1);
        }
}//GEN-LAST:event_remove_buttonActionPerformed
    public ArrayList<String> getVectorFiles() {
        ArrayList<String> names = new ArrayList<String>();
        for (int i = 0; i < model1.getSize(); i++) {
            names.add(model1.get(i).toString());
        }
        return names;
    }

    public void setVectorFiles(ArrayList<String> name) {
        for (int i = 0; i < name.size(); i++) {
            model1.addElement(name.get(i));
        }
    }
    private void output_add_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_output_add_button1ActionPerformed
        String name = SwingUtil.getOpenFileByChooser("Select output file", null, parent);
        if (name == null) {
            return;
        } else {
            Output.setText(name);
        }

        // TODO add your handling code here:
}//GEN-LAST:event_output_add_button1ActionPerformed

    private void OutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_OutputActionPerformed

    public boolean check() {
        if (model1.isEmpty()) {
            ReportInfo.reportValidate("Annotation_file is null, please check!");
            return false;
        }

        return SwingUtil.validateJTextNull(this);

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (!check()) {
            return;
        }
        annoFiles = getVectorFiles();

        Track[] tracks = new Track[annoFiles.size()];
        LoadTrackTask lt = new LoadTrackTask(annoFiles, tracks, null);
        NewProgress monitor = new NewProgress("Loading Annotation", StringRep.START, lt);
        monitor.startTask();
        if (monitor.getReturnStatus() != ForEverStatic.RET_OK) {
            if (monitor.getReturnStatus() == ForEverStatic.RET_ERR) {
                ReportInfo.reportError(null, monitor.getException());
            }
            return;
        }
        for (int i = 0; i < tracks.length; i++) {
            cdssListTrack.add(tracks[i]);
        }

        Track maintrack =ForMagic.getTracksBy(Main_annotaion.getText());
        if(maintrack==null)
        {
           return;
        }

        MergeAnnotationDialog amd = new MergeAnnotationDialog(parent, cdssListTrack,maintrack);

        MergePara.outputFile = Output.getText();
        if (Log.instance().reference.refile.equals(Refrenece.getText())) {
            MergePara.reference = Log.instance().reference;
        } else {
            MergePara.reference = new FastaFile(Refrenece.getText(), null);
        }

        doClose(ForEverStatic.RET_OK);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void RefreneceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreneceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefreneceActionPerformed

    private void ref_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ref_add_buttonActionPerformed
        String name = ForMagic.getFastaFile(parent);
        if (name == null) {
            return;
        } else {
            Refrenece.setText(name);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ref_add_buttonActionPerformed
    private void doClose(int retStatus) {
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList Annotation_file;
    private javax.swing.JTextField Main_annotaion;
    private javax.swing.JTextField Output;
    private javax.swing.JTextField Refrenece;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton main_add_button;
    private javax.swing.JButton output_add_button1;
    private javax.swing.JButton q_add_button;
    private javax.swing.JButton ref_add_button;
    private javax.swing.JButton remove_button;
    // End of variables declaration//GEN-END:variables
}
