/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Genotyper.java
 *
 * Created on 2009-10-10, 20:00:21
 */
package Magic.Analysis.Genotyping;

import Magic.Units.Gui.Task.GenotypingTask;
import Magic.WinMain.MagicFrame;
import Magic.Units.File.FileFormat;
import Magic.Units.File.Parameter.Log;
import Magic.Units.File.Parameter.StringRep;
import Magic.Units.Alignment.ProjectProperty;


import Magic.Units.File.Parameter.ForEverStatic;
import Magic.Units.Gui.Task.NewProgress;
import Magic.Units.Gui.Task.SwingWorker;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.broadinstitute.sting.utils.pileup.PileupElement;
import utils.FileUtil;
import utils.FormatCheck;
import utils.Gatk.GATKUtil;
import utils.ReportInfo;
import utils.ForMagic;
import utils.swing.FileChoose;
import utils.swing.SwingUtil;

/**
 *
 * @author Huabin Hou
 */
public class GenotyperJDialog extends javax.swing.JDialog {

    //public DataImportBean projectProperty;
//    public GenotyperBean genotyperBean = new GenotyperBean();
  //  private ProjectProperty dataImportBean;
    MagicFrame parent;
    private javax.swing.JTextField Variants = new javax.swing.JTextField();
    private javax.swing.JTextField VCF_OUT = new javax.swing.JTextField();
    private javax.swing.JTextField sampleName = new javax.swing.JTextField();
    private DefaultListModel algnModel = new DefaultListModel();

    /** Creates new form Genotyper */
    public GenotyperJDialog(java.awt.Frame parent) {
        super(parent, true);
        this.parent = (MagicFrame) parent;
       // this.dataImportBean = Log.instance().projectProperty;
        initComponents();
       // SwingUtil.init(org.broadinstitute.sting.gatk.walkers.genotyper.UnifiedGenotyper.class, this);
        referenceFile.setText(Log.instance().reference.refile);
        for (String readFile : Log.instance().reads.getReads()) {
            algnModel.addElement(readFile);
        }
        outPath.setText(FileUtil.getNoTypePart(ForEverStatic.CURRENT_PATH));
        SwingUtil.setLocation(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display_button = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        LOD_THRESHOLD_label = new javax.swing.JLabel();
        CONFIDENCE_THRESHOLD = new javax.swing.JTextField();
        baseModel_label = new javax.swing.JLabel();
        baseModel = new javax.swing.JComboBox();
        heterozygosity_label = new javax.swing.JLabel();
        heterozygosity = new javax.swing.JTextField();
        defaultPlatform_label = new javax.swing.JLabel();
        defaultPlatform = new javax.swing.JComboBox();
        MAX_DELETIONS_label = new javax.swing.JLabel();
        MAX_DELETIONS = new javax.swing.JTextField();
        MAX_READS_IN_PILEUP_label = new javax.swing.JLabel();
        MAX_READS_IN_PILEUP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ref_add_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        referenceFile = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        readsList = new javax.swing.JList();
        algn_add_button = new javax.swing.JButton();
        remove_button1 = new javax.swing.JButton();
        VARIANTS_FILE_label = new javax.swing.JLabel();
        outPath = new javax.swing.JTextField();
        var_out_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        display_button.setFont(new java.awt.Font("Times New Roman", 0, 12));
        display_button.setText("OK");
        display_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_buttonActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Genotype Parameters", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Times New Roman", 0, 12));

        LOD_THRESHOLD_label.setText("Confidence Threshold");

        CONFIDENCE_THRESHOLD.setText("5");
        CONFIDENCE_THRESHOLD.setMinimumSize(new java.awt.Dimension(72, 21));

        baseModel_label.setText("Base Model");

        baseModel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EMPIRICAL", "ONE_STATE", "THREE_STATE" }));
        baseModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseModelActionPerformed(evt);
            }
        });

        heterozygosity_label.setText("Heterozygosity  ");
        heterozygosity_label.setToolTipText("Example:chr1:43000000-43100000");

        heterozygosity.setText("1e-3");

        defaultPlatform_label.setText("Sequencer Platform");

        defaultPlatform.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SOLEXA     ", "ROCHE454", "SOLID", "UNKNOWN " }));
        defaultPlatform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultPlatformActionPerformed(evt);
            }
        });

        MAX_DELETIONS_label.setText("Max Deletions");

        MAX_DELETIONS.setText("1");
        MAX_DELETIONS.setMinimumSize(new java.awt.Dimension(72, 21));

        MAX_READS_IN_PILEUP_label.setText("Max Coverage");

        MAX_READS_IN_PILEUP.setText("10000");
        MAX_READS_IN_PILEUP.setToolTipText("Maximum reads at this locus for it to be callable; to disable, provide value < 1 [default:10,000]");
        MAX_READS_IN_PILEUP.setMinimumSize(new java.awt.Dimension(72, 21));

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heterozygosity_label)
                    .addComponent(LOD_THRESHOLD_label)
                    .addComponent(MAX_DELETIONS_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MAX_DELETIONS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(heterozygosity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(CONFIDENCE_THRESHOLD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MAX_READS_IN_PILEUP_label, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baseModel_label, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaultPlatform_label))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MAX_READS_IN_PILEUP, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(defaultPlatform, javax.swing.GroupLayout.Alignment.TRAILING, 0, 106, Short.MAX_VALUE)
                    .addComponent(baseModel, javax.swing.GroupLayout.Alignment.TRAILING, 0, 106, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heterozygosity_label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heterozygosity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAX_READS_IN_PILEUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAX_READS_IN_PILEUP_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LOD_THRESHOLD_label)
                    .addComponent(CONFIDENCE_THRESHOLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baseModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baseModel_label))
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MAX_DELETIONS_label)
                    .addComponent(MAX_DELETIONS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaultPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaultPlatform_label))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main Parameters", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel6.setFont(new java.awt.Font("Times New Roman", 0, 12));

        ref_add_button.setFont(new java.awt.Font("Times New Roman", 0, 12));
        ref_add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        ref_add_button.setMargin(new java.awt.Insets(0, 4, 0, 4));
        ref_add_button.setMaximumSize(new java.awt.Dimension(29, 29));
        ref_add_button.setMinimumSize(new java.awt.Dimension(29, 29));
        ref_add_button.setPreferredSize(new java.awt.Dimension(29, 29));
        ref_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ref_add_buttonActionPerformed(evt);
            }
        });

        jLabel5.setText("Reference File");

        jLabel3.setText("Indexed BAM File");

        referenceFile.setFont(new java.awt.Font("Times New Roman", 0, 12));
        referenceFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenceFileActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");

        readsList.setFont(new java.awt.Font("Times New Roman", 0, 16));
        readsList.setModel(algnModel);
        jScrollPane2.setViewportView(readsList);

        algn_add_button.setFont(new java.awt.Font("Times New Roman", 0, 12));
        algn_add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        algn_add_button.setMargin(new java.awt.Insets(0, 4, 0, 4));
        algn_add_button.setMaximumSize(new java.awt.Dimension(29, 29));
        algn_add_button.setMinimumSize(new java.awt.Dimension(29, 29));
        algn_add_button.setPreferredSize(new java.awt.Dimension(29, 29));
        algn_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algn_add_buttonActionPerformed(evt);
            }
        });

        remove_button1.setFont(new java.awt.Font("Times New Roman", 0, 16));
        remove_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/remove.png"))); // NOI18N
        remove_button1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        remove_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_button1ActionPerformed(evt);
            }
        });

        VARIANTS_FILE_label.setText("Output Path");

        outPath.setFont(new java.awt.Font("Times New Roman", 0, 12));
        outPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outPathActionPerformed(evt);
            }
        });

        var_out_button.setFont(new java.awt.Font("Times New Roman", 0, 12));
        var_out_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        var_out_button.setMargin(new java.awt.Insets(2, 2, 2, 2));
        var_out_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_out_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(VARIANTS_FILE_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(outPath, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(referenceFile, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(algn_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remove_button1)
                    .addComponent(ref_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(var_out_button))
                .addGap(24, 24, 24))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(referenceFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ref_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(algn_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remove_button1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VARIANTS_FILE_label)
                        .addComponent(outPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(var_out_button)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(display_button))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(display_button)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void var_out_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_out_buttonActionPerformed
        // String name = SwingUtil.getOpenFileByChooser("OUTPUT", null, parent);
        FileChoose fc = new FileChoose(JFileChooser.DIRECTORIES_ONLY, ForEverStatic.CURRENT_PATH, null, null, parent);
        String name = fc.getFileNameImplement();
        if (name == null) {
            return;
        }
        ForEverStatic.CURRENT_PATH = FileUtil.getFilePath(name);
        outPath.setText(name);
    }//GEN-LAST:event_var_out_buttonActionPerformed

    private void outPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outPathActionPerformed
    private boolean check() {
        if (referenceFile.getText() == null || referenceFile.getText().equals("")) {
            ReportInfo.reportValidate("Please input reference sequence file");
            return false;
        } else if (algnModel.isEmpty()) {
            ReportInfo.reportValidate("Please input BAM file");
            return false;
        } else if (outPath.getText() == null || outPath.getText().equals("")) {
            ReportInfo.reportValidate("Please input variant output file");
            return false;
        }/* else if (!FormatCheck.isRegion(intervals.getText())) {
            ReportInfo.reportValidate("Region format error");
            return false;
        }*/
        return true;
    }

    private void display_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_buttonActionPerformed

       // if (!SwingUtil.validateField(org.broadinstitute.sting.gatk.walkers.genotyper.UnifiedGenotyper.class, this)) {

            //return;
       // }
        if (!check()) {
            return;
        }

        if (Log.instance().global.Qualty_SCORE_ADD == 64) {
            PileupElement.QUALITY_SUB = 31;
        } else {
            PileupElement.QUALITY_SUB = 0;

        }

         ArrayList<String> readfiles = getReadsFiles();
     //   final ArrayList<String> cmd = SwingUtil.getGATKArgumentString(org.broadinstitute.sting.gatk.walkers.genotyper.UnifiedGenotyper.class, this);
//
      //  final String[] cmdArray = cmd.toArray(new String[0]);

       // final GenotyperJDialog gd = this;
        this.setVisible(false);
         GenotypingTask lt = new GenotypingTask(referenceFile.getText(), readfiles);
         NewProgress monitor = new NewProgress("Loading Annotation", StringRep.START, lt);
            // monitor.startTask();
            if (monitor.getReturnStatus() != ForEverStatic.RET_OK) {
                //System.out.println("Error ");
                if (monitor.getReturnStatus() == ForEverStatic.RET_ERR) {
                    ReportInfo.reportError(null, monitor.getException());
                    return ;
                }

                return ;
            }

    }//GEN-LAST:event_display_buttonActionPerformed

    private void baseModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baseModelActionPerformed

    private void defaultPlatformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultPlatformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defaultPlatformActionPerformed

    private void ref_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ref_add_buttonActionPerformed
        String name = ForMagic.getFastaFile(parent);
        if (name == null) {
            return;
        }
        ////System.out.println(name+" name===================================");
        ForEverStatic.CURRENT_PATH = FileUtil.getFilePath(name);

        String fileType = FileFormat.checkFileFormatByContent(name);

        if (fileType.equals(StringRep.FASTA)) {
            referenceFile.setText(name);

        } else {
            int answerConfirmation = JOptionPane.showConfirmDialog(parent, "Not a fasta format file!", "ERROR", JOptionPane.DEFAULT_OPTION);
            switch (answerConfirmation) {
                case 0:
                case 1:
                    return;
            }

        }  // TODO add your handling code here:
    }//GEN-LAST:event_ref_add_buttonActionPerformed

    private void referenceFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenceFileActionPerformed
}//GEN-LAST:event_referenceFileActionPerformed

    private void remove_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_button1ActionPerformed
        int[] indices = readsList.getSelectedIndices();
        if (indices != null) {
            for (int i = indices.length - 1; i >= 0; i--) {
                algnModel.removeElementAt(indices[i]);
                //  model2.removeElementAt(indices[i]);
            }
            readsList.setSelectedIndex(-1);
        }        // TODO add your handling code here:
}//GEN-LAST:event_remove_button1ActionPerformed

    private void algn_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algn_add_buttonActionPerformed
        //String name = SwingUtil.getOpenFileByChooser(null, new String[]{"fasta|fa"}, parent);
        String[] files = ForMagic.getAlignmentFiles(parent);
        if (files == null || files.length == 0) {
            return;
        }
        ForEverStatic.CURRENT_PATH = files[0];
        String unexistFile = "";
        String format = "";
        for (int i = 0; i < files.length; i++) {
            String name = files[i];
            format = FileFormat.checkFileFormatByContent(name);
            if (FileFormat.checkSurportedAlignFile(format)) {
                algnModel.addElement(name);

            } else {

                unexistFile = unexistFile + "\t" + name;
            }
        }
        if (!unexistFile.equals("")) {
            JOptionPane.showMessageDialog(this, "Not surported  format, please check:\n" + unexistFile, "Warnning", JOptionPane.OK_OPTION);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_algn_add_buttonActionPerformed
   private ArrayList<String> getReadsFiles() {
        return SwingUtil.getFilesByModel(algnModel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CONFIDENCE_THRESHOLD;
    private javax.swing.JLabel LOD_THRESHOLD_label;
    private javax.swing.JTextField MAX_DELETIONS;
    private javax.swing.JLabel MAX_DELETIONS_label;
    private javax.swing.JTextField MAX_READS_IN_PILEUP;
    private javax.swing.JLabel MAX_READS_IN_PILEUP_label;
    private javax.swing.JLabel VARIANTS_FILE_label;
    private javax.swing.JButton algn_add_button;
    private javax.swing.JComboBox baseModel;
    private javax.swing.JLabel baseModel_label;
    private javax.swing.JComboBox defaultPlatform;
    private javax.swing.JLabel defaultPlatform_label;
    private javax.swing.JButton display_button;
    private javax.swing.JTextField heterozygosity;
    private javax.swing.JLabel heterozygosity_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField outPath;
    private javax.swing.JList readsList;
    private javax.swing.JButton ref_add_button;
    private javax.swing.JTextField referenceFile;
    private javax.swing.JButton remove_button1;
    private javax.swing.JButton var_out_button;
    // End of variables declaration//GEN-END:variables
}
