/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestPanel.java
 *
 * Created on Dec 7, 2009, 2:06:12 PM
 */
package test;

import Magic.Units.File.Parameter.Log;
import java.awt.Font;
import java.awt.FontMetrics;

/**
 *
 * @author lenovo
 */
public class TestPanel extends javax.swing.JPanel {
  public  Integer DNA_FONT_WIDTH = 11;
    public  Integer DNA_FONT_HEIGHT = 17;
    /** Creates new form TestPanel */
    public TestPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] argvs) {
        TestPanel test = new TestPanel();
        FontMetrics fm = test.getFontMetrics(new Font("Dialog", Font.PLAIN, 16));
        int DNA_FONT_WIDTH = fm.charWidth('A');
        int DNA_FONT_HEIGHT = fm.getAscent();
        //System.out.println(DNA_FONT_WIDTH);
        //System.out.println(DNA_FONT_HEIGHT);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
