/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OptionDialog.java
 *
 * Created on Feb 25, 2009, 7:53:15 PM
 */

package Magic.Options.Alignment;


import Magic.WinMain.MagicFrame;
import utils.swing.ExpandPanel.SettingPanel;
import Magic.Options.Annotation.ViewModePanel;
import java.util.Vector;
import javax.swing.JPanel;

/**
 *
 * @author QIJ
 */
public class AlignmentOptionDialog extends javax.swing.JDialog {

    private MagicFrame trackFrame;
    //private FontPanel font_panel;

    private FontChoosePanel fontChoosePanel;
   private   StringShowModePanel stringShowModePanel;
      private BaseColorPanel readsColorPanel;
       private RefBaseColorPanel refColorPanel;
   //     private PileBaseColorPanel pileColorPanel;
     //private BackGroundColorPanel backgroundColorPanel;
   
    /** Creates new form OptionDialog */
    public AlignmentOptionDialog(MagicFrame parent) {
        super(parent, false);
        initComponents();
        setTitle("Alignment Option");

        trackFrame=parent;
        initValues();
    }

    public void initValues()
    {
        Vector<String> names = new Vector<String>();
        Vector<JPanel> panels = new Vector<JPanel>();
        Vector<Boolean> expand = new Vector<Boolean>();

        //font_panel = new FontPanel(trackFrame);
        fontChoosePanel = new FontChoosePanel(trackFrame);
        readsColorPanel = new BaseColorPanel(trackFrame);
        refColorPanel= new RefBaseColorPanel(trackFrame);
        stringShowModePanel= new StringShowModePanel(trackFrame);
      //  pileColorPanel= new PileBaseColorPanel(trackFrame);

        //names.add("Font");
        //panels.add(font_panel);
        //expand.add(false);

        names.add("Font");
        panels.add(fontChoosePanel);
        expand.add(true);

        names.add("Show Base String");
        panels.add(stringShowModePanel);
        expand.add(true);

        names.add("Read Base Color");
        panels.add(readsColorPanel);
        expand.add(false);

         names.add("Reference And HightLight Base Color");
        panels.add(refColorPanel);
        expand.add(false);

       

        SettingPanel exp_panel = new SettingPanel(names, panels, expand, this);
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(exp_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(exp_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        this.pack();

       //Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x=200;
        int y=100;
        this.setLocation(x, y);     //为dialog设置位置

    
        this.setVisible(true);
    }

    public void update(MagicFrame parent)
    {
        trackFrame=parent;
       // reads_height_panel.update(trackFrame);
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 216, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
