/*
 * FontPanel.java
 *
 * Created on October 16, 2008, 9:04 AM
 */
package Magic.Options.Alignment;

import Magic.WinMain.MagicFrame;
import Magic.Units.File.Parameter.Log;

/**
 *
 * @author Huabin Hou
 */
public class StringShowModePanel extends javax.swing.JPanel {

    private MagicFrame trackFrame;

    /** Creates new form FontPanel */
    public StringShowModePanel(MagicFrame parent) {
        trackFrame = parent;
        initComponents();
        if (trackFrame.dataRep != null) {
            initValues();
        }
    }

    public void initValues() {
        if (Log.instance().alignPara.showHighlightString) {
            highlight.setSelected(true);
        }
        if (Log.instance().alignPara.showReadString) {
            read.setSelected(true);
        }
        if (Log.instance().alignPara.showRefString) {
            ref.setSelected(true);
        }
         if (Log.instance().alignPara.showReadArrow) {
            arrow.setSelected(true);
        }
         if (Log.instance().alignPara.showReadBorder) {
            border.setSelected(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        border = new javax.swing.JCheckBox();
        arrow = new javax.swing.JCheckBox();
        ref = new javax.swing.JCheckBox();
        read = new javax.swing.JCheckBox();
        highlight = new javax.swing.JCheckBox();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        border.setText("Show Border");
        border.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderActionPerformed(evt);
            }
        });

        arrow.setText("Show Arrow");
        arrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrowActionPerformed(evt);
            }
        });

        ref.setText("Show Reference Base String");
        ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refActionPerformed(evt);
            }
        });

        read.setText("Show Simple Read Base String");
        read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readActionPerformed(evt);
            }
        });

        highlight.setText("Show Highlight Read Base String");
        highlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highlightActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(ref, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 231, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(read, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 212, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(highlight))
                    .add(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(arrow, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(border, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(ref)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(read)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(highlight)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(arrow)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(border)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void borderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderActionPerformed
    Log.instance().alignPara.showReadBorder = border.isSelected();
     trackFrame.resetAssembly();
    // TODO add your handling code here:
}//GEN-LAST:event_borderActionPerformed

private void arrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrowActionPerformed
    Log.instance().alignPara.showReadArrow = arrow.isSelected();
     trackFrame.resetAssembly();
}//GEN-LAST:event_arrowActionPerformed

private void refActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refActionPerformed
  // TODO add your handling code here:
    if (ref.isSelected() == Log.instance().alignPara.showRefString) {
    } else {
        Log.instance().alignPara.showRefString = ref.isSelected();
    }
    trackFrame.resetAssembly();    // TODO add your handling code here:
}//GEN-LAST:event_refActionPerformed

private void readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readActionPerformed
// TODO add your handling code here:
    if (read.isSelected() == Log.instance().alignPara.showReadString) {
    } else {
        Log.instance().alignPara.showReadString = read.isSelected();
    }
    trackFrame.resetAssembly();    // TODO add your handling code here:
}//GEN-LAST:event_readActionPerformed

private void highlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highlightActionPerformed
  if (highlight.isSelected() == Log.instance().alignPara.showHighlightString) {
    } else {
        Log.instance().alignPara.showHighlightString = highlight.isSelected();
    }
    trackFrame.resetAssembly();    // TODO add your handling code here:
}//GEN-LAST:event_highlightActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox arrow;
    private javax.swing.JCheckBox border;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox highlight;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JCheckBox read;
    private javax.swing.JCheckBox ref;
    // End of variables declaration//GEN-END:variables
}
