/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MessageDialog.java
 *
 * Created on Feb 25, 2009, 7:07:09 PM
 */

package Magic.Search;

import Magic.WinMain.MagicFrame;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JTextPane;

/**
 *
 * @author QIJ
 */
public class MessageDialog extends javax.swing.JDialog {

    MagicFrame trackFrame;
    public JTextPane base_pane;
    /** Creates new form MessageDialog */
    public MessageDialog(MagicFrame parent, boolean modal, int x, int y) {
        super(parent, modal);
        this.setTitle("Message");
        initComponents();

        trackFrame=parent;
        initComponents();
        initValues();

        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x1=x-this.getPreferredSize().width;
        if(x1<10) x1=10;
        int y1=y;
        if(y1>screen.height-this.getPreferredSize().height) y1=screen.height-this.getPreferredSize().height;
        this.setLocation(x1,y1);
        this.toBack();
        //System.out.println("message");
    }

    public void appendMessage(String message)
    {
        base_pane.setText(base_pane.getText()+message+"\n");
    }

    public void initValues()
    {
        base_pane = new JTextPane();
        Font font = new Font("Monospace", 0, 14);
        base_pane.setBackground(Color.white);

        base_pane.setFont(font);
        base_pane.setEditable(true);
        base_pane.setText("Message\n");

        jScrollPane1.setViewportView(base_pane);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
