/*
 * SNPListPanel.java
 *
 * Created on November 17, 2008, 1:55 PM
 */

package Magic.Search;

import Magic.Units.Piece.Piece;
import Magic.WinMain.MagicFrame;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author  QIJ
 */
public class ResultsListPanel extends javax.swing.JPanel {

    Vector<Piece>list_vec=new Vector<Piece>();
    public int current_page=0;
    public int page_num=0;
    public final int MAX_NUM=20;
    AnnoListDialog search_dialog;
    DefaultListModel list_model;

    String ID="";
    /** Creates new form SNPListPanel */
    public ResultsListPanel(AnnoListDialog parent,String id) {
        search_dialog=parent;
        ID=id;
        list_model=new DefaultListModel();
        initComponents();
    }
    
    public void setData(Vector<Piece> vec) {
        if(vec==null) return;
        list_vec=vec;

        current_page=0;
        page_num=list_vec.size()/MAX_NUM;
        if(list_vec.size()%MAX_NUM!=0) page_num++;
        
        list_model=(DefaultListModel)result_list.getModel();
        list_model.clear();
        updatePage();
    }

    private void updatePage() {
        list_model.removeAllElements();
        int min=current_page*MAX_NUM;
        int max=(current_page+1)*MAX_NUM-1;
        if(max>list_vec.size()-1) max=list_vec.size()-1;
        for(int i=min;i<=max;i++) {
          //  System.out.println(list_vec.elementAt(i).toDetailString());
            list_model.addElement(list_vec.elementAt(i).toSearchString());
        }
        page_label.setText("page "+(current_page+1)+"/"+page_num);
        count_label.setText("list "+(min+1)+" - "+(max+1)+" of "+list_vec.size());
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        result_list = new javax.swing.JList();
        prev_button = new javax.swing.JButton();
        next_button = new javax.swing.JButton();
        page_label = new javax.swing.JLabel();
        count_label = new javax.swing.JLabel();

        setFont(new java.awt.Font("Times New Roman", 0, 12));

        result_list.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        result_list.setModel(list_model);
        result_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                result_listValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(result_list);

        prev_button.setFont(new java.awt.Font("Times New Roman", 0, 12));
        prev_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/left_small.png"))); // NOI18N
        prev_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prev_buttonActionPerformed(evt);
            }
        });

        next_button.setFont(new java.awt.Font("Times New Roman", 0, 12));
        next_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/right_small.png"))); // NOI18N
        next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_buttonActionPerformed(evt);
            }
        });

        page_label.setFont(new java.awt.Font("Times New Roman", 0, 12));
        page_label.setText("page 0/0");

        count_label.setFont(new java.awt.Font("Times New Roman", 0, 12));
        count_label.setForeground(new java.awt.Color(0, 51, 255));
        count_label.setText("list 0 - 0 of 0");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(prev_button)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(next_button)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(page_label)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(count_label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );

        layout.linkSize(new java.awt.Component[] {next_button, prev_button}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(next_button)
                    .add(prev_button)
                    .add(count_label)
                    .add(page_label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {next_button, prev_button}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents

    private void result_listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_result_listValueChanged
// TODO add your handling code here:    
    if(result_list.getSelectedIndex()<0) return;
    int index=current_page*MAX_NUM+result_list.getSelectedIndex();
    Piece piece=list_vec.elementAt(index);
     MagicFrame.instance.gotoPieceSite(piece);
}//GEN-LAST:event_result_listValueChanged

private void prev_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev_buttonActionPerformed
    // TODO add your handling code here:
    if(current_page==0) return;
    current_page--;
    updatePage();
}//GEN-LAST:event_prev_buttonActionPerformed

private void next_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_buttonActionPerformed
    // TODO add your handling code here:    
    if(current_page>=page_num-1) return;
    current_page++;
    updatePage();
}//GEN-LAST:event_next_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel count_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton next_button;
    private javax.swing.JLabel page_label;
    private javax.swing.JButton prev_button;
    private javax.swing.JList result_list;
    // End of variables declaration//GEN-END:variables

}
