/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OptionDialog.java
 *
 * Created on Feb 25, 2009, 7:53:15 PM
 */

package Magic.Options.Annotation;


import Magic.WinMain.MagicFrame;
import utils.swing.ExpandPanel.SettingPanel;
import java.util.Vector;
import javax.swing.JPanel;

/**
 *
 * @author QIJ
 */
public class AnnotationOptionDialog extends javax.swing.JDialog {

    private MagicFrame trackFrame;
    //private FontPanel font_panel;

    private ViewModePanel view_panel;
    private TrackHeightPanel reads_height_panel;
    private TrackColorPanel reads_color_panel;
    private TrackBiasPanel reads_bias_panel;
    private RowHeightPanel row_height_panel;
    private RowBGPanel row_bg_panel;
    /** Creates new form OptionDialog */
    public AnnotationOptionDialog(java.awt.Frame parent,boolean modal, MagicFrame a) {
        super(parent, modal);
        initComponents();
         setTitle("Annotation Option");

        trackFrame=a;
        initValues();
    }

    public void initValues()
    {
        Vector<String> names = new Vector<String>();
        Vector<JPanel> panels = new Vector<JPanel>();
        Vector<Boolean> expand = new Vector<Boolean>();

        //font_panel = new FontPanel(trackFrame);
        view_panel = new ViewModePanel(trackFrame);
  
        reads_height_panel = new TrackHeightPanel(trackFrame);
        reads_color_panel = new TrackColorPanel(trackFrame);
        reads_bias_panel = new TrackBiasPanel(trackFrame);
        row_height_panel = new RowHeightPanel(trackFrame);
        row_bg_panel = new RowBGPanel(trackFrame);

        //names.add("Font");
        //panels.add(font_panel);
        //expand.add(false);

        names.add("View");
        panels.add(view_panel);
        expand.add(true);

        /*names.add("Read Setting");
        panels.add(reads_setting_panel);
        expand.add(true);*/

        names.add("Unit Height");
        panels.add(reads_height_panel);
        expand.add(true);


         names.add("Track Height");
        panels.add(row_height_panel);
        expand.add(false);

        names.add("Unit Color");
        panels.add(reads_color_panel);
        expand.add(false);

        names.add("Unit Vertical Space");
        panels.add(reads_bias_panel);
        expand.add(false);

       

        names.add("Track Background");
        panels.add(row_bg_panel);
        expand.add(false);

        SettingPanel exp_panel = new SettingPanel(names, panels, expand, this);
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(exp_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(exp_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        this.pack();

       //Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x=200;
        int y=100;
        this.setLocation(x, y);     //为dialog设置位置

       /* Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x=screen.width-this.getPreferredSize().width-20;
        int y=100;
        this.setLocation(x, y);*/
        this.setVisible(true);
    }

    public void update(MagicFrame parent)
    {
        trackFrame=parent;
        reads_height_panel.update(trackFrame);
        reads_color_panel.update(trackFrame);
        reads_bias_panel.update(trackFrame);
        row_height_panel.update(trackFrame);
        row_bg_panel.update(trackFrame);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 216, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
