/*
 * ReadsColorPanel.java
 *
 * Created on October 16, 2008, 11:06 AM
 */
package Magic.Options.Annotation;

import utils.swing.EditorAndRenterer.JPanelEditor;
import utils.swing.EditorAndRenterer.JPanelRenderer;
import Magic.WinMain.MagicFrame;
import java.awt.Color;
import java.util.Vector;
import javax.swing.JCheckBox;
import javax.swing.JColorChooser;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import utils.swing.SwingUtil;

/**
 *
 * @author Huabin Hou
 */
public class TrackColorPanel extends javax.swing.JPanel {

    private MagicFrame trackFrame;

    /** Creates new form ReadsColorPanel */
    public TrackColorPanel(MagicFrame parent) {
        trackFrame = parent;
        initComponents();
        if(trackFrame.dataRep!=null) initTable();
    }

    public void initTable() {

        DefaultTableModel dm = (DefaultTableModel) reads_color_table.getModel();
        while (dm.getRowCount() > 0) {
            dm.removeRow(0);
        }
        
        for (int i = 0; i < trackFrame.dataRep.trackNum; i++) {
            Vector<Object> vector = new Vector<Object>();
            String s1 = "" + (i + 1);
            String s2 = trackFrame.dataRep.tracks[i].trackSet.name;
            vector.add(s1);
            vector.add(s2);



        JPanel panel = new JPanel();
            panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
            panel.setBackground(trackFrame.dataRep.tracks[i].trackSet.COLOR);
            panel.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    JPanel panel = (JPanel) evt.getSource();
                    Color color = JColorChooser.showDialog(panel, "show", panel.getBackground());
                    if (color != null) {
                        panel.setBackground(color);
                        int index = -1;
                        JTable table = (JTable) panel.getParent();

                        for (int i = 0; i < table.getRowCount(); i++) {
                            if (table.getValueAt(i, 2).equals(panel)) {
                                index = i;
                                break;
                            }
                        }
                        if (index >= 0) {
                            trackFrame.receiveReadsColor(index,color);
                        }
                    }
                }
            });
            vector.add(panel);//     

           //  JPanel panel=SwingUtil.getColorPanel(trackFrame.dtrunk.tracks[i].trackSet.COLOR, "Magic.Options.Alignment.BackGroundColorPanel", "setColor", this);
          
            dm.addRow(vector);
        }
        
        reads_color_table.getColumn(reads_color_table.getColumnName(2)).setCellRenderer(new JPanelRenderer());
        reads_color_table.getColumn(reads_color_table.getColumnName(2)).setCellEditor(new JPanelEditor(new JCheckBox()));

    }

    public void update(MagicFrame parent)
    {
        trackFrame=parent;
        initTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        reads_color_table = new javax.swing.JTable();

        setFont(new java.awt.Font("Times New Roman", 0, 12));

        jScrollPane4.setFont(new java.awt.Font("Times New Roman", 0, 12));

        reads_color_table.setFont(new java.awt.Font("Times New Roman", 0, 12));
        reads_color_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Row", "Name", "Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reads_color_table.setColumnSelectionAllowed(true);
        reads_color_table.setRowHeight(22);
        reads_color_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(reads_color_table);
        reads_color_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        reads_color_table.getColumnModel().getColumn(0).setResizable(false);
        reads_color_table.getColumnModel().getColumn(0).setPreferredWidth(20);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable reads_color_table;
    // End of variables declaration//GEN-END:variables
}
