/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DesignPirmerMainPanel.java
 *
 * Created on Dec 4, 2009, 10:11:43 AM
 */
package Magic.Analysis.Primer;

import utils.swing.ExpandPanel.ExpandPanelAbstract;
import Magic.IO.DataRep;
import Magic.WinMain.MagicFrame;
import Magic.Units.File.Parameter.Log;
import Magic.Units.File.FastaFile;
import Magic.Units.File.FileFormat;
import Magic.Units.File.Parameter.ForEverStatic;
import Magic.Units.Track.Track;
import javax.swing.JPanel;
import utils.FileUtil;
import utils.ReportInfo;
import utils.ForMagic;
import utils.swing.SwingUtil;

/**
 *
 * @author Huabin Hou
 */
public class PirmerDesignPathPanel extends JPanel implements ExpandPanelAbstract {

    private PrimerDesignDialog primerDialog;
    private Track variantTrack;
    private MagicFrame parent;

    /** Creates new form DesignPirmerMainPanel */
    public PirmerDesignPathPanel(PrimerDesignDialog primerDialog, MagicFrame parent) {
        initComponents();
        this.parent = parent;
        this.primerDialog = primerDialog;
        this.variantTrack = primerDialog.getVariantTrack();
        this.Reference.setText(Log.instance().reference.refile);

        this.variantTrack = primerDialog.getVariantTrack();
        if (this.variantTrack != null) {
            this.Variant.setText(variantTrack.trackSet.filename);
            this.Output.setText(FileUtil.getParentPath(variantTrack.trackSet.filename) + ForEverStatic.FILE_SEPARATOR + "primer");
        }
    }

    private boolean check() {
        return SwingUtil.validateJTextNull(this);

    }

    public void setSelectFields() {
        try {
            primerDialog.primer3.outputPath = Output.getText();
            if (Log.instance().reference.refile.equals(Reference.getText())) {
                primerDialog.primer3.reference = Log.instance().reference;
            } else {
                primerDialog.primer3.reference = new FastaFile(Reference.getText(), null);
            }
            Track maintrack = ForMagic.getTracksBy(Variant.getText());
            if (maintrack == null) {
                return;
            }
            primerDialog.primer3.mainAnnoTrack = maintrack;

        } catch (Exception e) {
            ReportInfo.reportError("", e);
        }
    }

    public boolean setting() {
        if (check()) {
            setSelectFields();
            return true;
        } else {
            return false;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        Variant = new javax.swing.JTextField();
        outputAddButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Reference = new javax.swing.JTextField();
        ref_add_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Output = new javax.swing.JTextField();
        variantAddButton = new javax.swing.JButton();

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Setting File Path", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Times New Roman", 0, 12));

        Variant.setFont(new java.awt.Font("Times New Roman", 0, 12));
        Variant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariantActionPerformed(evt);
            }
        });

        outputAddButton.setFont(new java.awt.Font("Times New Roman", 0, 12));
        outputAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        outputAddButton.setMargin(new java.awt.Insets(0, 4, 0, 4));
        outputAddButton.setMaximumSize(new java.awt.Dimension(29, 29));
        outputAddButton.setMinimumSize(new java.awt.Dimension(29, 29));
        outputAddButton.setPreferredSize(new java.awt.Dimension(29, 29));
        outputAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputAddButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Variant");

        jLabel4.setText("Reference");

        Reference.setFont(new java.awt.Font("Times New Roman", 0, 12));
        Reference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReferenceActionPerformed(evt);
            }
        });

        ref_add_button.setFont(new java.awt.Font("Times New Roman", 0, 12));
        ref_add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        ref_add_button.setMargin(new java.awt.Insets(2, 2, 2, 2));
        ref_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ref_add_buttonActionPerformed(evt);
            }
        });

        jLabel7.setText("Output");

        Output.setFont(new java.awt.Font("Times New Roman", 0, 12));
        Output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputActionPerformed(evt);
            }
        });

        variantAddButton.setFont(new java.awt.Font("Times New Roman", 0, 12));
        variantAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        variantAddButton.setMargin(new java.awt.Insets(0, 4, 0, 4));
        variantAddButton.setMaximumSize(new java.awt.Dimension(29, 29));
        variantAddButton.setMinimumSize(new java.awt.Dimension(29, 29));
        variantAddButton.setPreferredSize(new java.awt.Dimension(29, 29));
        variantAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variantAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(Reference, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ref_add_button))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Output, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                            .addComponent(Variant, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(variantAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(Reference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ref_add_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Variant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(variantAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(outputAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VariantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VariantActionPerformed

    private void outputAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputAddButtonActionPerformed
        String name = SwingUtil.getOpenFileByChooser("Select output path", null, parent);
        if (name == null) {
            return;
        } else {
            Output.setText(name);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_outputAddButtonActionPerformed

    private void ReferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReferenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReferenceActionPerformed

    private void ref_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ref_add_buttonActionPerformed
        String name = ForMagic.getFastaFile(parent);
        if (name == null) {
            return;
        } else {
            Reference.setText(name);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ref_add_buttonActionPerformed

    private void OutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutputActionPerformed

    private void variantAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variantAddButtonActionPerformed
        String name = SwingUtil.getOpenFileByChooser("Select variant file", null, parent);
        if (name == null) {
            return;
        } else {
            Variant.setText(name);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_variantAddButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Output;
    private javax.swing.JTextField Reference;
    private javax.swing.JTextField Variant;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton outputAddButton;
    private javax.swing.JButton ref_add_button;
    private javax.swing.JButton variantAddButton;
    // End of variables declaration//GEN-END:variables
}
