/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HintDialog.java
 *
 * Created on Dec 29, 2009, 4:40:33 PM
 */
package Magic.Units.Gui;

import Magic.Units.File.Parameter.LogImplement;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.UIManager;
import utils.ReportInfo.InfoType;
import utils.swing.SwingUtil;

/**
 *
 * @author lenovo
 */
public class InfoDialog extends javax.swing.JDialog {

    /** Creates new form HintDialog */
    public InfoDialog(java.awt.Frame parent, InfoType infoType) {
        super(parent, false);
        initComponents();
        setIcon(infoType);
        messageArea.setLineWrap(true);
        messageArea.setWrapStyleWord(true);
        SwingUtil.setLocation(this);
    }
    private static InfoDialog log;

    public static InfoDialog instance(java.awt.Frame see, InfoType type) {
        if (log == null) {
            log = new InfoDialog(see, type);
        }
        return log;
    }

    private void setIcon(InfoType infoType) {
        jLabel1.setIcon(getInfoIcon(infoType));

    }

    private Icon getInfoIcon(InfoType infoType) {
        switch (infoType) {
            case error:
                return ((Icon) UIManager.get("OptionPane.errorIcon"));
            case warning:
                return ((Icon) UIManager.get("OptionPane.warningIcon"));
            case information:
                return ((Icon) UIManager.get("OptionPane.informationIcon"));
            case question:
                return ((Icon) UIManager.get("OptionPane.questionIcon"));
        }
        return null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setAutoscrolls(true);

        messageArea.setColumns(20);
        messageArea.setRows(5);
        messageArea.setText(" *** Error!!! ***\n");
        jScrollPane1.setViewportView(messageArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 370, 160));

        cancelButton.setFont(new java.awt.Font("Times New Roman", 0, 12));
        cancelButton.setText("OK");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 30, 30));

        jLabel1.setText("    ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 30));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 10, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose();
}//GEN-LAST:event_cancelButtonActionPerformed
    private void doClose() {
        setVisible(false);
        dispose();
    }

    public void setMessage(String message) {
        messageArea.setText(message);
    }

    public void appendMessage(String message) {
        int len = messageArea.getText().length() + 1;
        messageArea.append("\n" + message);
        messageArea.setCaretPosition(len);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageArea;
    // End of variables declaration//GEN-END:variables
}
